/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./pbr/crewneck.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/crewneck.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.crewneck_back.geometry} material={materials.crewneck_front} />
      <mesh geometry={nodes.crewneck_collar.geometry} material={materials.crewneck_front} />
      <mesh geometry={nodes.crewneck_front.geometry} material={materials.crewneck_front} />
      <mesh geometry={nodes.crewneck_sleeve_left.geometry} material={materials.crewneck_front} />
      <mesh geometry={nodes.crewneck_sleeve_right.geometry} material={materials.crewneck_front} />
      <mesh geometry={nodes.Mesh002.geometry} material={materials.crewneck_inside} />
      <mesh geometry={nodes.Mesh002_1.geometry} material={materials.sweatband} />
      <mesh geometry={nodes.Mesh002_2.geometry} material={materials.label} />
    </group>
  )
}

useGLTF.preload('/crewneck.gltf')
