export * from './configuratorDesign';
export { useColorStore } from './useColorStore';
export type { PartGradient, PartGradients } from './useGradientStore';
export { useGradientStore } from './useGradientStore';
export type { NameInstance } from './useNameStore';
export { DEFAULT_NAME_TEXT, NAME_DECAL_DEPTH, useActiveNameInstance, useNameStore } from './useNameStore';
export type { NumberInstance } from './useNumberStore';
export { DEFAULT_NUMBER_TEXT, NUMBER_DECAL_DEPTH, NUMBER_DECAL_SCALE_MAX, NUMBER_DECAL_SCALE_MIN, useNumberStore } from './useNumberStore';
export type { PatternItem } from './usePatternStore';
export { PATTERNS, SHIRT_PARTS, usePatternStore } from './usePatternStore';
export { useSelectionStore } from './useSelectionStore';
export { useStepsStore } from './useStepsStore';
export { NECK_DEFAULT_COLOR } from '@constants';
export type { MeshRefs, PartColors, PartPatterns, ShirtPart } from '@types';
